config/routes.rb
Rails.application.routes.draw do
  resources :shelly_users

end

app/models/shelly_user.rb
require 'bcrypt'

class ShellyUser
  include Mongoid::Document
	include Mongoid::Timestamps
	include BCrypt

	field :username, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
	field :encrypted_password, type: String
  field :description, type: String
  field :activated, type: Mongoid::Boolean

	attr_accessor :password, :username, :first_name, :last_name, :email, :description

	before_save :encrypt_password
	after_save :clear_password

	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

	
	validates_presence_of :username
	validates_uniqueness_of :username
	validates_length_of :username, minimum: 3, maximum: 20
 	
  validates_presence_of :email
	validates_uniqueness_of :email
	validates_format_of :email, with: EMAIL_REGEX

	validates_confirmation_of :password
	validates_presence_of :password
	validates_length_of :password, minimum: 6, maximum: 20, on: :create

	validates_presence_of :password_confirmation

	validates_presence_of :first_name
	validates_length_of :first_name, minimum: 1, maximum: 50
  
	validates_presence_of :last_name
	validates_length_of :last_name, minimum: 1, maximum: 50

	private		
		attr_accessor :salt		

		def encrypt_password
			if password.present?
				self.salt = BCrypt::Engine.generate_salt
				self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
			end
		end

		def clear_password
			self.password = nil
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shelly_users_controller.rb
class ShellyUsersController < ApplicationController
  before_action :set_shelly_user, only: [:show, :edit, :update, :destroy]	

  # GET /shelly_users
  # GET /shelly_users.json
  def index
    @shelly_users = ShellyUser.all
  end

  # GET /shelly_users/1
  # GET /shelly_users/1.json
  def show
	end

  # GET /shelly_users/new
  def new
    @shelly_user = ShellyUser.new
  end

  # GET /shelly_users/1/edit
  def edit
  end

  # POST /shelly_users
  # POST /shelly_users.json
  def create
    @shelly_user = ShellyUser.new(shelly_user_params)

    respond_to do |format|
      if @shelly_user.safely.save
        format.html { redirect_to @shelly_user, notice: 'Shelly user was successfully created.' }
        format.json { render :show, status: :created, location: @shelly_user }
      else
        format.html { render :new }
        format.json { render json: @shelly_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shelly_users/1
  # PATCH/PUT /shelly_users/1.json
  def update
    respond_to do |format|
      if @shelly_user.update(shelly_user_params)
        format.html { redirect_to @shelly_user, notice: 'Shelly user was successfully updated.' }
        format.json { render :show, status: :ok, location: @shelly_user }
      else
        format.html { render :edit }
        format.json { render json: @shelly_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelly_users/1
  # DELETE /shelly_users/1.json
  def destroy
    @shelly_user.destroy
    respond_to do |format|
      format.html { redirect_to shelly_users_url, notice: 'Shelly user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shelly_user
      @shelly_user = ShellyUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shelly_user_params
      params.require(:shelly_user).permit(:first_name, :last_name, :email, :description, :password, :password_confirmation, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shelly_users_helper.rb
module ShellyUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shelly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shelly_users/_form.html.erb
<%= form_for(@shelly_user) do |f| %>
  <% if @shelly_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shelly_user.errors.count, "error") %> prohibited this shelly_user from being saved:</h2>

      <ul>
      <% @shelly_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
	<div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shelly_users/edit.html.erb
<h1>Editing Shelly User</h1>

<%= render 'form' %>

<%= link_to 'Show', @shelly_user %> |
<%= link_to 'Back', shelly_users_path %>

app/views/shelly_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shelly Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Description</th>
      <th>Activated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shelly_users.each do |shelly_user| %>
      <tr>
        <td><%= shelly_user.first_name %></td>
        <td><%= shelly_user.last_name %></td>
        <td><%= shelly_user.email %></td>
        <td><%= shelly_user.description %></td>
        <td><%= shelly_user.activated %></td>
        <td><%= link_to 'Show', shelly_user %></td>
        <td><%= link_to 'Edit', edit_shelly_user_path(shelly_user) %></td>
        <td><%= link_to 'Destroy', shelly_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shelly user', new_shelly_user_path %>

app/views/shelly_users/new.html.erb
<h1>New Shelly User</h1>

<%= render 'form' %>

<%= link_to 'Back', shelly_users_path %>

app/views/shelly_users/show.html.erb
<p id="notice"><%= notice %></p>
<%= YAML::dump(@shelly_user) %>

<p>
  <strong>Firstname:</strong>
  <%= @shelly_user.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @shelly_user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @shelly_user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shelly_user.description %>
</p>

<p>
  <strong>Activated:</strong>
  <%= @shelly_user.activated %>
</p>

<%= link_to 'Edit', edit_shelly_user_path(@shelly_user) %> |
<%= link_to 'Back', shelly_users_path %>